export enum OrderEventType {
  STOP_STARTED = "STOP_STARTED",
  STOP_ARRIVED = "STOP_ARRIVED",
  STOP_COMPLETED = "STOP_COMPLETED",
  STOP_CANCELED = "STOP_CANCELED",
  STOP_RETURNED = "STOP_RETURNED",
  STOP_CANCELLATION_REQUESTED = "STOP_CANCELLATION_REQUESTED",
  STOP_CANCELLATION_APPROVED = "STOP_CANCELLATION_APPROVED",
  STOP_CANCELLATION_REJECTED = "STOP_CANCELLATION_REJECTED",
  STOP_RETURN_REQUESTED = "STOP_RETURN_REQUESTED",
  STOP_RETURN_APPROVED = "STOP_RETURN_APPROVED",
  STOP_RETURN_REJECTED = "STOP_RETURN_REJECTED",
}