export enum OrderEventType {
  STOP_STARTED = "STOP_STARTED",
  STOP_ARRIVED = "STOP_ARRIVED",
  STOP_COMPLETED = "STOP_COMPLETED",
  STOP_CANCELED = "STOP_CANCELED",
  STOP_RETURNED = "STOP_RETURNED",
}